name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build using next-on-pages
        run: |
          # نحدد نسخة معروفة من next-on-pages لضمان الاستقرار
          npx @cloudflare/next-on-pages@1
        env:
          NODE_ENV: production

      - name: Show output folder (for debug)
        run: |
          echo "Listing .vercel/output directory (if exists):"
          ls -la .vercel || true
          ls -la .vercel/output || true
          ls -la .vercel/output/static || true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .vercel/output/static
